export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_CLEAR = "POST_CREATE_CLEAR"

export const POST_FETCH_REQUEST = "POST_FETCH_REQUEST";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const POST_FETCH_FAIL = "POST_FETCH_FAIL";
export const POST_FETCH_CLEAR = "POST_FETCH_CLEAR"

export const POST_FETCH_WITH_USER_ID_REQUEST = "POST_FETCH_WITH_USER_ID_REQUEST"
export const POST_FETCH_WITH_USER_ID_SUCCESS = "POST_FETCH_WITH_USER_ID_SUCCESS"
export const POST_FETCH_WITH_USER_ID_FAIL = "POST_FETCH_WITH_USER_ID_FAIL"
export const POST_FETCH_WITH_USER_ID_CLEAR = "POST_FETCH_WITH_USER_ID_CLEAR"