export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_UPDATE = "USER_LOGIN_UPDATE";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
export const USER_CREATE_CLEAR = "USER_CREATE_CLEAR"

export const USER_LIKED_POSTS_FETCH_REQUEST = "USER_LIKED_POSTS_FETCH_REQUEST"
export const USER_LIKED_POSTS_FETCH_SUCCESS = "USER_LIKED_POSTS_FETCH_SUCCESS"
export const USER_LIKED_POSTS_FETCH_FAIL = "USER_LIKED_POSTS_FETCH_FAIL"
export const USER_LIKED_POSTS_FETCH_CLEAR = "USER_LIKED_POSTS_FETCH_CLEAR"
export const USER_LIKED_POSTS_FETCH_INC = "USER_LIKED_POSTS_FETCH_INC"
export const USER_LIKED_POSTS_FETCH_DEC = "USER_LIKED_POSTS_FETCH_DEC"

export const USERS_ONLINE_UPDATE = "USERS_ONLINE_UPDATE"
export const USERS_ONLINE_CLEAR = "USERS_ONLINE_CLEAR"