require('dotenv').config()
const mongoose = require("mongoose");



const db_link = process.env.MONGO_URI

mongoose
.connect(db_link)
.then((db) => {
    console.log("notification db connected");
})
.catch((err) => {
    console.log(err.message);
});

const notificationSchema = mongoose.Schema({
    type:{
        type: String,
        required: true
    },
    generatedByUser:{
        type: mongoose.Schema.ObjectId,
        ref: "userModel",
        require: [true, "notification must be generated by a user"]
    },
    targetPostId:{
        type: mongoose.Schema.ObjectId,
        ref: "postModel",
        default: null,
    },
    targetUserId:{
        type: mongoose.Schema.ObjectId,
        ref: "userModel",
        default: null,
    },
    receivers:{
        // array of users getting this notification
        type: Array,
        default: [],
        required: [true, "notification must be received by someone."]
    },
    content:{
        type: String,
        default: ""
    }
})

const notificationModel = mongoose.model('notificationModel', notificationSchema);

module.exports = notificationModel;